language: dart
os:
  - linux
sudo: required
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  - export PATH="$PATH:/usr/lib/dart/bin"
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - cd app_feup
  - ../flutter/bin/flutter doctor
  - ../flutter/bin/flutter packages get
script:
  - dartanalyzer --fatal-warnings --options analysis_options.yaml lib 
cache:
  directories:
    - $HOME/.pub-cache