name: uni_lint
description: Custom lint rules for Uni.
version: 1.0.0

publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  custom_lint_builder: ^0.7.6
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.4

dev_dependencies:
  test: ^1.26.2
