name: uni
description: A UP no teu bolso.

# The app version name is automatically bumped by CI.
# To change it manually, override the value in app_version.txt.
# The app version code is automatically also bumped by CI.
# Do not change it manually.
version: 2.2.0-beta.9+417

publish_to: "none" # We do not publish to pub.dev
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.35.6

dependencies:
  add_2_calendar_new: ^1.0.4
  app_links: ^6.4.1
  app_settings:
    git:
      url: https://github.com/spencerccf/app_settings.git
      ref: master
  battery_plus: ^7.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.3.0
  diacritic: ^0.1.6
  email_validator: ^3.0.0
  expandable: ^5.0.1
  expandable_page_view: ^1.0.17
  expansion_tile_card: ^3.0.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_marker_popup: ^8.1.0
  flutter_markdown: ^0.7.7+1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  flutter_widget_from_html_core: ^0.17.0
  html: ^0.15.6
  http: ^1.5.0
  image: ^4.5.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  latlong2: ^0.9.1
  logger: ^2.6.2
  material_design_icons_flutter: ^7.0.7296
  objectbox: ">=5.0.0 <5.1.0"
  objectbox_flutter_libs: any
  open_file: ^3.5.10
  openid_client:
    git:
      url: https://github.com/NIAEFEUP/openid_client.git
      ref: v0.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  plausible_analytics: ^0.3.0
  sentry_flutter: ^9.7.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  synchronized: ^3.4.0
  timelines: ^0.1.0
  ua_client_hints: ^1.4.1
  uni_ui: ^1.0.0
  up_menus: ^1.0.1
  upgrader: ^12.1.0
  url_launcher: ^6.3.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: "4ce065"

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.7.6
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^18.0.0
  mockito: ^5.5.0
  objectbox_generator: any
  sqflite_common_ffi: ^2.3.6
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/
    - assets/text/
    - assets/text/locations/
    - assets/text/calendar/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icon/adaptive_background.png"
  adaptive_icon_foreground: "assets/icon/icon_dark.png"
  adaptive_icon_monochrome: "assets/icon/icon_dark.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_ios: true
  image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

flutter_native_splash:
  color: "#280709"
  android_12:
    image: assets/images/blank_splash.png
    color: "280709"
