name: uni
description: A UP no teu bolso.

publish_to: 'none' # We do not publish to pub.dev

# The app version name is automatically bumped by CI.
# To change it manually, override the value in app_version.txt.
# The app version code is automatically also bumped by CI.
# Do not change it manually.
version: 1.7.17+207

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.6

dependencies:
  add_2_calendar: ^2.2.4
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  connectivity_plus: ^5.0.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.5
  email_validator: ^2.0.1
  encrypt: ^5.0.3
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.0.0
  flutter_markdown: ^0.6.0
  flutter_svg: ^2.0.0+1
  flutter_widget_from_html_core: ^0.10.3
  html: ^0.15.0
  http: ^1.1.0
  image: ^4.0.13
  intl: ^0.18.0
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  material_design_icons_flutter: ^7.0.7296
  open_file_plus: ^3.4.1
  path: ^1.8.0
  path_provider: ^2.0.0
  percent_indicator: ^4.2.2
  provider: ^6.0.4
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.0.3
  shimmer: ^3.0.0
  sqflite: ^2.0.3
  synchronized: ^3.0.0
  timelines: ^0.1.0
  tuple: ^2.0.0
  url_launcher: ^6.0.2
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  # FIXME(luisd): Update mockito to a release version when 5.4.3 or above
  # is launched
  mockito:
    git:
      url: https://github.com/dart-lang/mockito.git
      ref: "e54a006"
  test: any
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/text/
    - assets/text/locations/
    - assets/meal-icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
    - family: LocationIcons
      fonts:
        - asset: assets/fonts/LocationIcons.ttf

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#75171E"
  adaptive_icon_foreground: "assets/icon/android_icon_foreground.png"

flutter_intl:
  enabled: true
