name: uni_ui
description: User interface components for the Uni app.
version: 1.0.0

publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.6 <3.36.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.5
  phosphor_flutter: ^2.1.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  leancode_lint: ^18.0.0
  uni_lint: ^1.0.0
  test: ^1.26.2

flutter:
  assets:
    - assets/images/
  uses-material-design: true
